# ~/.bashrc: executed by bash(1) for non-login shells.

export LS_OPTIONS='--color=auto'
eval "`dircolors`"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'
alias grep='grep --color=auto'

PS1="\[\033[1;36m\]\u@\[\033[0;36m\]\H:\[\033[1;32m\]\w\[\033[00m\]🌀 "

PATH=$PATH:/opt/puppetlabs/bin